// Copyright (C) 2006 Philip Aston
// All rights reserved.
//
// This file is part of The Grinder software distribution. Refer to
// the file LICENSE which is part of The Grinder distribution for
// licensing details. The Grinder distribution is available on the
// Internet at http://grinder.sourceforge.net/
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
// FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
// COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
// HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
// STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
// OF THE POSSIBILITY OF SUCH DAMAGE.

package net.grinder.plugin.http.tcpproxyfilter;

import net.grinder.tools.tcpproxy.ConnectionDetails;


/**
 * A listener for events generated by {@link HTTPRequestFilter} and
 * {@link HTTPResponseFilter}.
 *
 * <p>
 * Public as it is wired by PicoContainer.
 * </p>
 *
 * @author Philip Aston
 */
public interface HTTPFilterEventListener {

  /**
   * A connection has been opened.
   *
   * @param connectionDetails Connection details.
   */
  void open(ConnectionDetails connectionDetails);

  /**
   * Part of a request message has been received.
   *
   * @param connectionDetails Connection details.
   * @param buffer Buffer containing message.
   * @param bytesRead Length of message.
   */
  void request(
    ConnectionDetails connectionDetails, byte[] buffer, int bytesRead);

  /**
   * Part of a response message has been received.
   *
   * @param connectionDetails Connection details.
   * @param buffer Buffer containing message.
   * @param bytesRead Length of message.
   */
  void response(
    ConnectionDetails connectionDetails, byte[] buffer, int bytesRead);

  /**
   * A connection has been closed.
   *
   * @param connectionDetails Connection details.
   */
  void close(ConnectionDetails connectionDetails);
}
